# Use root/example as user/password credentials
version: "3.8"

volumes:
  default_mongodb_data:

services:
  default_mongodb:
    restart: "always"
    build:
      context: .
      target: default_mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - "default_mongodb_data:/data/db"
    healthcheck:
      interval: 5s
      timeout: 5s
      retries: 3

  mongo-express:
    restart: "always"
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@default_mongodb:27017/
