version: "3.8"

volumes:
  mysqldb_data:

services:
  mysqldb:
    restart: "always"
    build:
      context: .
      target: mysqldb
    ports:
      - "3306:3306"
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: dockerdb
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker_pass
    volumes:
      - mysqldb_data:/var/lib/mysql

  # adminer:
  #   restart: "always"
  #   image: adminer
  #   ports:
  #     - "8080:8080"
  #   environment:
  #     ADMINER_DESIGN: "dracula"
  #   depends_on:
  #     - mysqldb
